# Generated by Django 4.1.4 on 2022-12-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('maker', models.CharField(max_length=255)),
                ('general_name', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('category', models.CharField(default='uncategorized', max_length=255)),
                ('category2', models.CharField(max_length=255)),
                ('sub_categoryOne', models.CharField(max_length=255)),
                ('sub_categoryTwo', models.CharField(max_length=255)),
                ('country_of_origin', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('imgURL1', models.CharField(max_length=255, null=True)),
                ('imgURL2', models.CharField(max_length=255, null=True)),
                ('imgURL3', models.CharField(max_length=255, null=True)),
                ('weight', models.IntegerField()),
                ('size_one', models.IntegerField()),
                ('price', models.IntegerField()),
                ('shipping', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
