# Generated by Django 4.1.4 on 2022-12-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_productdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productdata',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='productdata',
            name='sub_categoryOne',
        ),
        migrations.RemoveField(
            model_name='productdata',
            name='sub_categoryTwo',
        ),
        migrations.AddField(
            model_name='productdata',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.genre'),
        ),
    ]
